/* tests/test_gguf.mjs — JS GGUF reader vs original fp32 fixture.
 *
 * Reads tests/mini.gguf (generated by gen_gguf_fixture.py) and
 * tests/mini_expect.json. For each tensor in the expectation file:
 *   - calls JS GGUF.dequant(name)
 *   - compares the first 8 values to the original fp32 source values
 *     within the format's quantisation budget
 *
 *   F32 / F16  → max-err ≤ 1e-4
 *   Q8_0       → max-err ≤ 0.6 × max(|w|) / 127
 *   Q4_K       → max-err ≤ (range / 15) × 0.6  (4-bit per-sub-block)
 */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { GGUF } from '../lib/gguf.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const buf    = await readFile(resolve(__dirname, 'mini.gguf'));
const expect = JSON.parse(await readFile(resolve(__dirname, 'mini_expect.json'), 'utf8'));

const gf = new GGUF(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

console.log(`== test_gguf ==`);
console.log(`  GGUF version=${gf.version}, ${gf.nTensors} tensors, ${gf.nKv} kv`);
console.log(`  arch=${gf.kv['general.architecture']} name=${gf.kv['general.name']}`);

let pass = 0, fail = 0;

for (const ex of expect.tensors) {
    const got = gf.dequant(ex.name);
    if (got.length !== ex.n_elements) {
        console.log(`  ✗ [FAIL] ${ex.name}: got ${got.length} elements, expected ${ex.n_elements}`);
        fail++;
        continue;
    }
    // Tolerance per dtype.
    // Q8 / Q4_K block-quant tolerance has to account for the block's
    // own max-abs (which can be far larger than the first 8 sampled
    // values). Use the dequantised tensor's global max-abs as a proxy
    // — it bounds any block scale from above for the synthetic data.
    let tol;
    if (ex.dtype === 'F32' || ex.dtype === 'F16') {
        tol = 1e-3;
    } else if (ex.dtype === 'Q8_0') {
        let mx = 0; for (let k = 0; k < got.length; k++) {
            const a = Math.abs(got[k]); if (a > mx) mx = a;
        }
        tol = Math.max(0.6 * mx / 127, 1e-4);
    } else if (ex.dtype === 'Q4_K') {
        let mx = 0; for (let k = 0; k < got.length; k++) {
            const a = Math.abs(got[k]); if (a > mx) mx = a;
        }
        tol = Math.max(2 * mx / 15, 0.05);
    } else {
        tol = 1.0;
    }

    let maxErr = 0;
    for (let i = 0; i < 8; i++) {
        const e = Math.abs(got[i] - ex.first8[i]);
        if (e > maxErr) maxErr = e;
    }
    const ok = maxErr <= tol;
    const tag = ok ? '✓ [PASS]' : '✗ [FAIL]';
    console.log(`  ${tag} ${ex.dtype.padEnd(5)} ${ex.name.padEnd(45)}  ` +
                `n=${ex.n_elements}  max-err=${maxErr.toExponential(2)}  tol=${tol.toExponential(2)}`);
    ok ? pass++ : fail++;
}

console.log(`\n== ${pass} PASS, ${fail} FAIL ==`);
process.exit(fail ? 1 : 0);
